# Generated by Django 4.2 on 2023-04-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('email', models.EmailField(max_length=254)),
                ('times_of_wa_password', models.IntegerField(default=0, verbose_name='一天内密码输错次数')),
                ('forbiden_start_time', models.DateTimeField(default=None, verbose_name='禁止登陆开始时间')),
                ('sevendays_autologin_start_time', models.DateTimeField(default=None, verbose_name='设置自动登录开始时间')),
            ],
        ),
    ]
